import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

const mainFont = Lato({
  subsets: ["latin"],
  weight: "100"
});

export const metadata: Metadata = {
  title: "Car Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.className} mx-auto max-w-screen-2xl`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
