import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";
import { GlobalContextProvider } from "@/context/globalContext";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const mainFont = Lato({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Car Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} text-black`}>
        <GlobalContextProvider>
          <Header />
          {children}
          <Footer />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
